apiVersion: kubelb.k8c.io/v1alpha1
kind: TCPLoadBalancer
metadata:
  name: swiss-army-knife   # user servicename
  namespace: default       # user clustername
spec:
  endpoints:
    - addresses:
        - ip: 168.119.243.175
        - ip: 168.119.152.165
      ports:
        - name: a-port
          port: 32544
          protocol: TCP
        - name: b-port
          port: 32627
          protocol: TCP
  ports:
    - name: a-port
      port: 8080
      protocol: TCP
    - name: b-port
      port: 8081
      protocol: TCP
  type: ClusterIP
