# Copyright 2020 The KubeLB Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
presubmits:
  - name: pull-kubelb-mod-verify
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubelb.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: golang:1.19
          command:
            - make
          args:
            - check-dependencies
          resources:
            requests:
              cpu: 1

  - name: pull-kubelb-lint
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubelb.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: golangci/golangci-lint:v1.50
          command:
            - make
          args:
            - lint
          resources:
            requests:
              cpu: 800m
              memory: 4Gi

  - name: pull-kubelb-yamllint
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubelb.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.19-node-18-kind-0.16-2
          command:
            - make
          args:
            - yamllint
          resources:
            requests:
              cpu: 200m

  - name: pull-kubelb-verify-boilerplate
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubelb.git"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.19-node-18-kind-0.16-2
          command:
            - make
          args:
            - verify-boilerplate

  - name: pull-kubelb-build
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubelb.git"
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: golang:1.19
          command:
            - make
          args:
            - all
          resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 2

postsubmits:
  - name: ci-push-kubelb
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubelb.git"
    branches:
      - ^main
      # Match on tags
      - ^v\d+\.\d+\.\d+.*
    reporter_config:
      slack:
        channel: dev-kubelb
    labels:
      preset-docker-push: "true"
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.19-node-18-kind-0.16-2
          command:
            - /bin/bash
            - -c
            - >-
              set -euo pipefail &&
              /usr/local/bin/entrypoint.sh &&
              docker login -u $QUAY_IO_USERNAME -p $QUAY_IO_PASSWORD quay.io &&
              make download-gocache docker-image-publish
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 500m

  - name: ci-push-kubelb-upload-gocache
    always_run: true
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubelb.git"
    branches:
      - ^main$
    reporter_config:
      slack:
        channel: dev-kubelb
    labels:
      preset-goproxy: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.19-node-18-kind-0.16-2
          command:
            - "./hack/ci-upload-gocache.sh"
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
