apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: manager
  name: system

---
apiVersion: v1
kind: Service
metadata:
  name: envoycp
  namespace: system
  labels:
    control-plane: manager
spec:
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    control-plane: manager
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: manager
spec:
  selector:
    matchLabels:
      control-plane: manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: manager
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: controller:latest
          name: manager
          ports:
            - containerPort: 8001
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 10
