apiVersion: v2
name: kubelb-manager
description: Helm chart for KubeLB Manager
type: application
maintainers:
  - name: Kubermatic
    email: support@kubermatic.com

# Helm chart Version.
version: v0.6.0
# Application version to be deployed.
appVersion: v0.6.0
