apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kubelb
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: kubelb-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: kubelb-metrics-service
  namespace: kubelb
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: kubelb
