apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: kubelb
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: kubelb
  namespace: system
