apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kuberentes.io/instance: kubelb
    app.kubernetes.io/component: rbac
    app.kubernetes.io/part-of: kubelb
  name: kubelb
  namespace: kubelb
