#!/usr/bin/env bash

# Copyright 2025 The KubeLB Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 

set -euo pipefail

cd $(dirname $0)/..
source hack/lib.sh

if [ "$#" -lt 1 ] || [ "$1" == "--help" ]; then
  cat << EOF
Usage: $(basename $0) (version)
where:
    version:    Gateway API version to download, e.g. v1.1.0
Example:
    $(basename $0) v1.1.0
EOF
  exit 0
fi

version="$1"

STANDARD_DIR="internal/resources/static/gateway-api/manifests/standard"
EXPERIMENTAL_DIR="internal/resources/static/gateway-api/manifests/experimental"

BASE_URL="https://github.com/kubernetes-sigs/gateway-api/releases/download/${version}"
STANDARD_URL="${BASE_URL}/standard-install.yaml"
EXPERIMENTAL_URL="${BASE_URL}/experimental-install.yaml"

TEMP_DIR=$(mktemp -d)
trap "rm -rf ${TEMP_DIR}" EXIT

echodate "Downloading Gateway API CRDs version: ${version}"

download_crds() {
  local channel=$1
  local url=$2
  local target_dir=$3
  local temp_file="${TEMP_DIR}/${channel}-install.yaml"

  echodate "Downloading ${channel} channel CRDs from ${url}..."
  if ! wget -q -O "${temp_file}" "${url}"; then
    echodate "Failed to download ${channel} CRDs from ${url}"
    exit 1
  fi
  if [[ ! -s "${temp_file}" ]]; then
    echodate "Downloaded file is empty for ${channel} channel"
    exit 1
  fi
  if ! grep -q "kind: CustomResourceDefinition" "${temp_file}" 2> /dev/null; then
    echodate "Downloaded file does not contain CRDs for ${channel} channel"
    head -5 "${temp_file}" 2> /dev/null || true
    exit 1
  fi
  mkdir -p "${target_dir}"
  cat > "${target_dir}/gateway-api-crds.yaml" << EOF
# Gateway API ${channel} channel CRDs
# Version: ${version}
# Downloaded from: ${url}
# Generated on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# DO NOT EDIT: This file is auto-generated by hack/update-gateway-api-crds.sh

EOF
  cat "${temp_file}" >> "${target_dir}/gateway-api-crds.yaml"
  echodate "${channel} channel CRDs saved to ${target_dir}/gateway-api-crds.yaml"
}

download_crds "standard" "${STANDARD_URL}" "${STANDARD_DIR}"
download_crds "experimental" "${EXPERIMENTAL_URL}" "${EXPERIMENTAL_DIR}"

echodate "Successfully downloaded Gateway API CRDs!"
echodate "Files created:"
echodate "   ${STANDARD_DIR}/gateway-api-crds.yaml"
echodate "   ${EXPERIMENTAL_DIR}/gateway-api-crds.yaml"
