# permissions for end users to edit globalloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalloadbalancer-editor-role
rules:
- apiGroups:
  - kubelb.k8c.io
  resources:
  - globalloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubelb.k8c.io
  resources:
  - globalloadbalancers/status
  verbs:
  - get
