# permissions for end users to view globalloadbalancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalloadbalancer-viewer-role
rules:
- apiGroups:
  - kubelb.k8c.io
  resources:
  - globalloadbalancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubelb.k8c.io
  resources:
  - globalloadbalancers/status
  verbs:
  - get
