apiVersion: v1
kind: Namespace
metadata:
  labels:
^^    control-plane: agent
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: system
  labels:
    control-plane: agent
spec:
  selector:
    matchLabels:
      control-plane: agent
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: agent
    spec:
      containers:
        - command:
            - /agent
          #        args:
          #        - --enable-leader-election
          image: controller:latest
          name: agent
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
          volumeMounts:
            - name: kubelb-cfg
              mountPath: "/home/nonroot/.kube/"
              readOnly: true
      volumes:
        - name: kubelb-cfg
          configMap:
            name: kubelb-cfg
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 10
